// This file has been autogenerated from parsing an Objective-C header file added in Xcode.
using Xamarin.Themes;
using System;

#if __UNIFIED__
using UIKit;
using Foundation;
#else
using MonoTouch.UIKit;
using MonoTouch.Foundation;
#endif

namespace ThemeSample {
	public partial class ListThemeController : UIViewController {
		public ListThemeController (IntPtr handle) : base (handle)
		{
		}

		Recipe[] recipes;

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			recipes = DataLoader.GetRecipes ();

			DishTableView.WeakDelegate = this;
			DishTableView.WeakDataSource = this;
			DishTableView.BackgroundColor = UIColor.Clear;
			DishTableView.SeparatorStyle = UITableViewCellSeparatorStyle.None;


			FoodyTheme.Apply (View);
			Title = "Dishes";
		}

		[Obsolete ("Deprecated in iOS 6.0")]
		public override void ViewDidUnload ()
		{
			base.ViewDidUnload ();
			ReleaseDesignerOutlets ();
		}

		[Export ("tableView:heightForRowAtIndexPath:")]
		float HeightForRow (UITableView tableView, NSIndexPath indexPath)
		{
			return 94;
		}

		[Export ("tableView:numberOfRowsInSection:")]
		int NumberOfRows (UITableView tableView, int section)
		{
			return recipes.Length;
		}

		const string CellIdentifier = "ThemeListCell";

		[Export ("tableView:cellForRowAtIndexPath:")]
		UITableViewCell CellForRow (UITableView tableView, NSIndexPath indexPath)
		{
			var cell = tableView.DequeueReusableCell (CellIdentifier) as ThemeListCell;
			cell.SelectionStyle = UITableViewCellSelectionStyle.None;
			var recipe = recipes [indexPath.Row];
			cell.Init (recipe);

			return cell;
		}

		[Export ("tableView:didSelectRowAtIndexPath:")]
		void DidSelectRow (UITableView tableView, NSIndexPath indexPath)
		{
			//PerformSegue ("detail", this);
		}

		public override void PrepareForSegue (UIStoryboardSegue segue, NSObject sender)
		{
			var detail = segue.DestinationViewController as DetailThemeController;
			detail.Recipe = recipes [DishTableView.IndexPathForSelectedRow.Row];

			base.PrepareForSegue (segue, sender);
		}
	}
}
