// This file has been autogenerated from parsing an Objective-C header file added in Xcode.using System;
using System;

#if __UNIFIED__
using UIKit;
using Foundation;
using CoreGraphics;
#else
using MonoTouch.UIKit;
using MonoTouch.Foundation;

using System.Drawing;
using CGRect = global::System.Drawing.RectangleF;
using CGPoint = global::System.Drawing.PointF;
using CGSize = global::System.Drawing.SizeF;
using nfloat = global::System.Single;
using nint = global::System.Int32;
using nuint = global::System.UInt32;
#endif


namespace ThemeSample {
	public partial class StepListCell : UITableViewCell {
		public StepListCell (IntPtr handle) : base (handle)
		{
		}

		public void Init (Recipe recipe, int step)
		{
			if (recipe == null)
				throw new ArgumentNullException ("recipe");

			if (step < 0 || step >= recipe.PreparationSteps.Length)
				throw new ArgumentException ("step");


			var ns = new NSString (recipe.PreparationSteps [step]);
			var stepSize = ns.StringSize (UIFont.SystemFontOfSize(14), new CGSize (220, 1000));

			StepLabel.Text = recipe.PreparationSteps [step];
			StepLabel.Lines = 0;

			var stepFrame = StepLabel.Frame;
			stepFrame.Height = stepSize.Height;
			StepLabel.Frame = stepFrame;

			step++;
			CountLabel.Text = "Step " + step.ToString ();
			BulletLabel.Text = step.ToString ();

		}

		protected override void Dispose (bool disposing)
		{
			ReleaseDesignerOutlets ();
			base.Dispose (disposing);
		}
	}
}
