// This file has been autogenerated from parsing an Objective-C header file added in Xcode.
using System;
using Xamarin.Themes;

#if __UNIFIED__
using UIKit;
using Foundation;
#else
using MonoTouch.UIKit;
using MonoTouch.Foundation;
#endif

namespace ThemeSample {
	public partial class MasterViewController : UIViewController {
		public MasterViewController (IntPtr handle) : base (handle)
		{
		}

		Recipe[] recipes;

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			recipes = DataLoader.GetRecipes ();

			var toolbarBg = FoodyTheme.SharedTheme.ToolbarBackgroundForSplitView (true);
			ToolbarBottom.SetBackgroundImage (toolbarBg, UIToolbarPosition.Bottom, UIBarMetrics.Default);

			var navbarBg = FoodyTheme.SharedTheme.NavigationBackgroundForSplitView (true);
			NavigationController.NavigationBar.SetBackgroundImage (navbarBg, UIBarMetrics.Default);

			DishTableView.WeakDelegate = this;
			DishTableView.WeakDataSource = this;
			DishTableView.BackgroundColor = UIColor.Clear;
			DishTableView.SeparatorStyle = UITableViewCellSeparatorStyle.None;

			var label = new UILabel ();
			label.BackgroundColor = UIColor.Clear;
			label.Font = UIFont.SystemFontOfSize (20);
			label.ShadowColor = UIColor.Black;
			label.TextAlignment = UITextAlignment.Center;
			label.TextColor = UIColor.White;
			NavigationItem.TitleView = label;

			label.Text = "Dishes";
			label.SizeToFit ();

			FoodyTheme.Apply (View);
		}

		public override void ViewWillAppear(bool animated)
		{
			base.ViewWillAppear(animated);

			DishTableView.SelectRow(NSIndexPath.FromRowSection(0,0),true, UITableViewScrollPosition.Top);
			DidSelectRow(DishTableView, NSIndexPath.FromRowSection(0,0));
		}

		[Export ("tableView:numberOfRowsInSection:")]
		int NumberOfRows (UITableView tableView, int section)
		{
			return recipes.Length;
		}

		[Export ("tableView:heightForRowAtIndexPath:")]
		float HeightForRow (UITableView tableView, NSIndexPath indexPath)
		{
			//return 43;
			return 94;
		}

		[Export ("tableView:didSelectRowAtIndexPath:")]
		void DidSelectRow (UITableView tableView, NSIndexPath indexPath)
		{
			var recipe = recipes [indexPath.Row];
			Delegate.SetRecipe (recipe);
		}

		const string CellIdentifier = "ThemeListCell";

		[Export ("tableView:cellForRowAtIndexPath:")]
		UITableViewCell CellForRow (UITableView tableView, NSIndexPath indexPath)
		{
			var cell = tableView.DequeueReusableCell (CellIdentifier) as ThemeListCell;
			//cell.SelectionStyle = UITableViewCellSelectionStyle.None;
			var recipe = recipes [indexPath.Row];
			cell.Init (recipe);

			return cell;
		}

		[Obsolete ("Deprecated in iOS 6.0")]
		public override void ViewDidUnload ()
		{
			base.ViewDidUnload ();
			ReleaseDesignerOutlets ();
		}

		public DetailThemeControllerIPad Delegate { get; set; }
	}
}
