// This file has been autogenerated from parsing an Objective-C header file added in Xcode.
using System;

#if __UNIFIED__
using UIKit;
using Foundation;
#else
using MonoTouch.UIKit;
using MonoTouch.Foundation;
#endif

namespace ThemeSample {
	public partial class StepsCell : UITableViewCell {
		public StepsCell (IntPtr handle) : base (handle)
		{
		}

		public void Init (string step, int index)
		{
			if (step == null)
				throw new ArgumentNullException ("step");
			if (index < 0)
				throw new ArgumentException ("index");

			var img = UIImage.FromFile ("ipad-dotted-pattern.png");
			DottedImageView.BackgroundColor = UIColor.FromPatternImage (img);

			StepLabel.Text = step;
			CountLabel.Text = "Step " + index.ToString ();
			BulletLabel.Text = index.ToString ();
		}

		protected override void Dispose (bool disposing)
		{
			ReleaseDesignerOutlets ();
			base.Dispose (disposing);
		}
	}
}
