// This file has been autogenerated from parsing an Objective-C header file added in Xcode.
using System;

#if __UNIFIED__
using UIKit;
using Foundation;
#else
using MonoTouch.UIKit;
using MonoTouch.Foundation;
#endif

namespace ThemeSample {
	public partial class ThemeListCell : UITableViewCell {
		public ThemeListCell (IntPtr handle) : base (handle)
		{
		}
         
		public void Init (Recipe item)
		{
			if (item == null)
				throw new ArgumentNullException ("item");

			DishImage.Image = item.Image;
			DishLabel.Text = item.Name;
			CountryButton.SetTitle (item.Country, UIControlState.Normal);
			TimeLabel.Text = item.PreparationTime;
		}

		protected override void Dispose (bool disposing)
		{
			ReleaseDesignerOutlets ();
			base.Dispose (disposing);
		}

		public override void SetSelected(bool selected, bool animated)
		{
			base.SetSelected(selected, animated);

			if (this.SelectionStyle != UITableViewCellSelectionStyle.None)
			{
				CellBackground.Hidden = this.Selected;
			}
		}
	}
}
